# Generated by Django 4.0.6 on 2022-07-29 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='name',
            field=models.CharField(default='DummyModel', max_length=255),
        ),
    ]
